@CLS@@TRUNCATE@@80COLS@
nhr===============================================================================

nhm                   _  _    __    ___  __    ___  _____  _  _
nhm                  ( \( )  /__\  / __)(  )  / __)(  _  )( \( )
nhm                   )  (  /(__)\( (__  )(__( (__  )(_)(  )  (
nhm                  (_)\_)(__)(__)\___)(____)\___)(_____)(_)\_)

nhy                        K e y n o t e   R e c a p

nhr-------------------------------------------------------------------------------
nhw                 P l a y   H a r d .   H a c k   H a r d e r .
nhr-------------------------------------------------------------------------------

nw                  May 31 - June 2, 2026  *  Carolina Beach, NC
nw                        Courtyard by Marriott Oceanfront

nhm                        naclcon.com  |  info@naclcon.com

nhr===============================================================================
n@TRUNCOFF@@WORDWRAP@
n
nhyLee Felsenstein
ncHomebrew Computing Club  *  Osborne 1  *  The History of Hacking keynote
nhr-------------------------------------------------------------------------------
n
nwlee felsenstein just finished his keynote and it was hopeful in an era that
nwfeels at times dystopian to many of us.

nwhe related our current era in computing to the mainframe days of the 60s
nwand early 70s. back then, tools were black boxes whose access was
nwrestricted to only a small cult of users who were "relieved of the need to
nwunderstand operation." on top of that, the hardware was so resource-heavy
nwand expensive that it was inaccessible to almost everyone.

nwof course, as people like felsenstein started to develop "micro" and
nw"personal" computing systems in the 70s and 80s, the reigning "powers that
nwbe" just kept doing what they always did: restricting knowledge of their
nwown systems (both hardware and software) to as few people as possible at
nwthe greatest possible expense.

nwas felsenstein said repeatedly in the talk, the mentality from those in
nwpower was "this you shall not know," and of course history is repeating
nwitself today. he made reference to bill gates' "open letter to hobbyists"
nwthat warned developers to "stop sharing the goddamned code" (my
nwparaphrase). that "knowledge for me, but not for you" mentality is alive
nwand strong today, where the people developing LLMs are training them on
nwother people's IP and then turning around and sending cease-and-desists to
nwthe developers of indy reverse-engineered projects (OpenClaw for instance).

nwso what does lee felsenstein think we should do about it? well, luckily we
nware hackers. we are those fringe, disempowered outcasts of society whose
nwprimary concerns, according to felsenstein, are virtuosity, the respect of
nwour similarly outcast peers, and the liberation of captive information.

nwwhat can we do in response to oppressive systems that are putting up rules
nwto restrict our access to knowledge and power?

nhyfelsenstein says, "we can violate the rules, which is our specialty."
n
nhr===============================================================================
