@CLS@@TRUNCATE@@80COLS@
nhr===============================================================================

nhm                   __                 _ _                _
nhm                  / _³ ___   ___   __³ ³ ³__   __ _ _ __³ ³ __
nhm                 ³ ³_ / _ \ / _ \ / _` ³ '_ \ / _` ³ '__³ ³/ /
nhm                 ³  _³ (_) ³ (_) ³ (_³ ³ ³_) ³ (_³ ³ ³  ³   <
nhm                 ³_³  \___/ \___/ \__,_³_.__/ \__,_³_³  ³_³\_\

^An^Ah^Ak          formerly NaClCON BBS, the unofficial board for NaClCON 2026

^An^Ah^Ac                      Missoula, Montana  *  naclconbbs.net

nhr===============================================================================
n@TRUNCOFF@@WORDWRAP@
nhyAbout This BBS
nhr-------------------------------------------------------------------------------
nwNaClCON BBS is the unofficial bulletin board for NaClCON 2026, the hacker
nwconference that ran on the coast of Carolina Beach, NC. The con is over;
nwthe board stayed. Chat, share files, and post in the message boards.

nhyKey Combos
nhr-------------------------------------------------------------------------------
nw  nhyCtrl-Unw  List users online         nhyCtrl-Pnw  Send a private message
nw  nhyCtrl-Tnw  Show time information     nhyCtrl-Onw  Toggle auto-pause
nw  nhy?nw       Display help menu         nhyQnw       Quit / go back

n