@CLS@@TRUNCATE@@80COLS@
nhr===============================================================================

nhm                   _  _    __    ___  __    ___  _____  _  _
nhm                  ( \( )  /__\  / __)(  )  / __)(  _  )( \( )
nhm                   )  (  /(__)\ ( (__  )(__( (__  )(_)(  )  (
nhm                  (_)\_)(__)(__) \___)(____) \___)(_____)(_)\_)

nhy                  T h e   H i s t o r y   o f   H a c k i n g

nhr-------------------------------------------------------------------------------
nhw                 P l a y   H a r d .   H a c k   H a r d e r .
nhr-------------------------------------------------------------------------------

nw                  May 31 - June 2, 2026  *  Carolina Beach, NC
nw                        Courtyard by Marriott Oceanfront

nhm                        naclcon.com  |  info@naclcon.com

nhr===============================================================================
n@TRUNCOFF@@WORDWRAP@
nhyAbout This BBS
nhr-------------------------------------------------------------------------------
nwNaClCON BBS is the official bulletin board for NaClCON 2026, the hacker
nwconference on the coast of Carolina Beach, NC. Connect before, during,
nwand after the con to chat, share files, and post in the message boards.

nhyKey Combos
nhr-------------------------------------------------------------------------------
nw  nhyCtrl-Unw  List users online         nhyCtrl-Pnw  Send a private message
nw  nhyCtrl-Tnw  Show time information     nhyCtrl-Onw  Toggle auto-pause
nw  nhy?nw       Display help menu         nhyQnw       Quit / go back

n